// GENERAL DEFINITIONS
`define TRUE 1'b1
`define FALSE 1'b0

// DEFINITIONS FOR THE STATE MACHINE
`define WAITING 3'b000
`define MENU 3'b010
`define BALANCE 3'b011
`define WITHDRAW 3'b100
`define DEPOSIT 3'b101
`define EXIT 3'b111


// DEFINITIONS FOR THE AUTHENTICATION
`define FIND_ACCOUNT 1'b0
`define AUTHENTICATE_ACCOUNT 1'b1
`define ACCOUNT_NOT_FOUND 1'b0
`define ACCOUNT_FOUND 1'b1
`define ACCOUNT_NOT_AUTHENTICATED 1'b0
`define ACCOUNT_AUTHENTICATED 1'b1
